### ISSUE TITLE
［CSS］インラインコード（<code>hoge</code>）のデザインがない

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/x-t9#140]
ブログを書くときに、コード部分にデザインがあると見やすいので、あると良いなと思いissue化しておきます

**Comment by doshimaf** [comment]
@kurudrive @goutetsuguma 
取り急ぎ、下記インラインコード用のCSSをカスタマイズ、自社サイトのカスタマイズの追加CSSに追加しています。
```css
.wp-block-post-content :not(pre)>code {
	display: inline-flex;
	margin: 0 0.5em;
	padding: 0.25em 0.5em;
	align-items: center;
	background-color: #f7f7f7;
	border: 1px solid #d9d9d9;
	border-radius: 2px;
	font-size: .9em;
	line-height: 1;
}
```


<img width="364" alt="スクリーンショット 2023-03-27 11 00 00" src="https://user-images.githubusercontent.com/73574599/227822973-8a1ab9d6-a44c-41ce-ac49-0cf5f8f0177c.png">

こちらのデザインで問題なければ、テーマ側に追加しようと思いますが、いかがでしょうか？
