### ISSUE TITLE
ステップブロックにコードブロックを配置するとコードブロックがはみ出す

### ISSUE THREAD

**Issue by doshimaf** [vektor-inc/x-t9#162]
https://www.vektor-inc.co.jp/post/github-actions-deploy/

下記のようにすることで、解消されそう。

```css
.vk_step .vk_step_item_content {
    display: grid;
    overflow: hidden; // これを追加する
}
```

```css
.hcb_wrap.hcb_wrap {
    display: block;
    margin-bottom: 2em;
    margin-top: 2em;
    padding: 0;
    position: relative;
    z-index: 0;
    overflow: auto; // これを追加する
}
